In [35]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity 

In [36]:
anime = pd.read_csv('anime.csv')

In [37]:
rating = pd.read_csv('rating.csv')

## 1. Content Based

In [38]:
anime['genre'] = anime['genre'].fillna('None')
anime['genre'] = anime['genre'].str.replace('[^\w\s]','')
anime

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                      Drama Romance School Supernatural  Movie        1   
1      Action Adventure Drama Fantasy Magic Military ...     TV       64   
2      Action Comedy Historical Parody Samurai SciFi ...     TV       51   
3                                         SciFi Thriller     TV       24   
4      Action Comedy Historical Parody Samurai SciFi ...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

In [39]:
countvec = CountVectorizer()

In [40]:
c = countvec.fit_transform(anime['genre'])
c

<12294x47 sparse matrix of type '<class 'numpy.int64'>'
	with 39630 stored elements in Compressed Sparse Row format>

In [41]:
print(countvec.get_feature_names())
print(c.toarray())

['action', 'adventure', 'ai', 'arts', 'cars', 'comedy', 'dementia', 'demons', 'drama', 'ecchi', 'fantasy', 'game', 'harem', 'hentai', 'historical', 'horror', 'josei', 'kids', 'life', 'magic', 'martial', 'mecha', 'military', 'music', 'mystery', 'none', 'of', 'parody', 'police', 'power', 'psychological', 'romance', 'samurai', 'school', 'scifi', 'seinen', 'shoujo', 'shounen', 'slice', 'space', 'sports', 'super', 'supernatural', 'thriller', 'vampire', 'yaoi', 'yuri']
[[0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
similarityScore = cosine_similarity(c.toarray())
print(similarityScore)

[[1.         0.18898224 0.         ... 0.         0.         0.        ]
 [0.18898224 1.         0.28571429 ... 0.         0.         0.        ]
 [0.         0.28571429 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 1.         1.         1.        ]
 [0.         0.         0.         ... 1.         1.         1.        ]]


## Anime Recommendation For Ali
#### Ali read anime_id #1

In [45]:
Ali = anime[anime['anime_id'] == 1].index[0]
Ali

22

In [47]:
similarAli = list(enumerate(similarityScore[Ali]))

In [ ]:
similarAli = sorted(similarAli, key=lambda x: x[1], reverse=True)
print(similarAli)

In [52]:
indexAli = []
for i in similarAli[1:6]:
    x = i[0]
    indexAli.append(x)
indexAli

[1465, 6568, 551, 1073, 1398]

In [53]:
judulAli = []
for i in indexAli:
    x = anime['name'].iloc[i]
    judulAli.append(x)
judulAli


['Cowboy Bebop: Yose Atsume Blues',
 'Seihou Tenshi Angel Links',
 'Seihou Bukyou Outlaw Star',
 'Waga Seishun no Arcadia',
 'Waga Seishun no Arcadia: Mugen Kidou SSX']

In [110]:
anime.iloc[indexAli]

anime_id                                      name  \
1465      4037           Cowboy Bebop: Yose Atsume Blues   
6568      1226                 Seihou Tenshi Angel Links   
551        400                 Seihou Bukyou Outlaw Star   
1073      2202                   Waga Seishun no Arcadia   
1398      2203  Waga Seishun no Arcadia: Mugen Kidou SSX   

                                                  genre     type episodes  \
1465          Action Adventure Comedy Drama SciFi Space  Special        1   
6568  Action Adventure Comedy Drama Romance SciFi Space       TV       13   
551                 Action Adventure Comedy SciFi Space       TV       24   
1073                 Action Adventure Drama SciFi Space    Movie        1   
1398                 Action Adventure Drama SciFi Space       TV       22   

      rating  members  
1465    7.53    19565  
6568    6.06     4817  
551     7.98    78600  
1073    7.70     4415  
1398    7.56     2587

## Anime Recommendation for Budi
#### Budi read anime_id #24 #25 #5

In [112]:
Budi1 = anime[anime['anime_id'] == 25].index[0]
Budi2 = anime[anime['anime_id'] == 24].index[0]
Budi3 = anime[anime['anime_id'] == 32281].index[0]
Budi1, Budi2, Budi3

(1432, 464, 0)

In [113]:
similarBudi1 = list(enumerate(similarityScore[Budi1]))
similarBudi2 = list(enumerate(similarityScore[Budi2]))
similarBudi3 = list(enumerate(similarityScore[Budi3]))

In [114]:
similarBudi1 = sorted(similarBudi1, key=lambda x: x[1], reverse=True)
similarBudi2 = sorted(similarBudi2, key=lambda x: x[1], reverse=True)
similarBudi3 = sorted(similarBudi3, key=lambda x: x[1], reverse=True)

In [115]:
animeBudi = []
for i in similarBudi1[1:4], similarBudi2[1:4], similarBudi2[1:4]:
    animeBudi.append(anime.iloc[i[0][0]])
    animeBudi.append(anime.iloc[i[1][0]])
    animeBudi.append(anime.iloc[i[2][0]])
animeBudi = pd.DataFrame(animeBudi)
animeBudi.drop_duplicates().sort_values(by='rating', ascending=False)



# for i in similarBudi1[1:4]:
#     print(i[0])

anime_id                                name  \
464         24                       School Rumble   
772        517     School Rumble Ichi Gakki Hoshuu   
1330     24627   Yamada-kun to 7-nin no Majo (OVA)   
2760     33713  Seihou Bukyou Outlaw Star Specials   
3974       297        Grenadier: Hohoemi no Senshi   
4486       370                      Burn Up Excess   

                                                  genre     type episodes  \
464                       Comedy Romance School Shounen       TV       26   
772                       Comedy Romance School Shounen      OVA        2   
1330                      Comedy Romance School Shounen      OVA        2   
2760                Action Adventure Comedy Ecchi SciFi  Special        2   
3974              Action Adventure Comedy Ecchi Shounen       TV       12   
4486  Action Adventure Comedy Ecchi Police SciFi Sho...       TV       13   

      rating  members  
464     8.06   178553  
772     7.85    40868  
1330    7.59    33816  
2760    7.16     1509  
3974    6.83    37919  
4486    6.71     6402

## Anime Recommendation for Cindy
#### Cindy read anime_id #10 #200

In [107]:
Cindy1 = anime[anime['anime_id'] == 100].index[0]
Cindy2 = anime[anime['anime_id'] == 200].index[0]
Cindy1, Cindy2

(2210, 1302)

In [108]:
similarCindy1 = list(enumerate(similarityScore[Cindy1]))
similarCindy2 = list(enumerate(similarityScore[Cindy2]))

In [116]:
similarCindy1 = sorted(similarCindy1, key= lambda x: x[1], reverse=True)
similarCindy2 = sorted(similarCindy2, key= lambda x: x[1], reverse=True)

In [118]:
animeCindy = []
for i in similarCindy1[1:4], similarCindy2[1:4]:
    animeCindy.append(anime.iloc[i[0][0]])
    animeCindy.append(anime.iloc[i[1][0]])
animeCindy = pd.DataFrame(animeCindy)
animeCindy

anime_id                                          name  \
1399       156                                             X   
233        372  Cardcaptor Sakura Movie 2: Fuuin Sareta Card   
4162       626                          Mamotte Shugogetten!   
4754       660                   Denshin Mamotte Shugogetten   

                                                  genre   type episodes  \
1399  Action Drama Fantasy Magic Romance Shoujo Supe...     TV       24   
233           Comedy Drama Fantasy Magic Romance Shoujo  Movie        1   
4162               Comedy Fantasy Magic Romance Shounen     TV       22   
4754               Comedy Fantasy Magic Romance Shounen    OVA        8   

      rating  members  
1399    7.56    51004  
233     8.28    60637  
4162    6.79     4995  
4754    6.64     2372

## Anime Recommendation for User_id = 1

In [ ]:
user_1 = rating[rating['user_id'] == 1].sort_values(by='rating', ascending=False)
user_1

In [128]:
user_1_index = user_1.iloc[:4].index
user_1_index[0]

47

In [129]:
similar_user1 = list(enumerate(similarityScore[user_1_index[0]]))
similar_user2 = list(enumerate(similarityScore[user_1_index[1]]))
similar_user3 = list(enumerate(similarityScore[user_1_index[2]]))
similar_user4 = list(enumerate(similarityScore[user_1_index[3]]))

In [130]:
similar_user1 = sorted(similar_user1, key= lambda x:x[1], reverse=True)
similar_user2 = sorted(similar_user2, key= lambda x:x[1], reverse=True)
similar_user3 = sorted(similar_user3, key= lambda x:x[1], reverse=True)
similar_user4 = sorted(similar_user4, key= lambda x:x[1], reverse=True)

In [ ]:
similar_user_1 = similar_user1 + similar_user2 + similar_user3 + similar_user4
similar_user_1 = sorted(similar_user_1, key=lambda x:x[1], reverse=True)
similar_user_1

In [136]:
animeUser1 = []
for i in similar_user_1[:4]:
    animeUser1.append(anime.iloc[i[0]])
animeUser1 = pd.DataFrame(animeUser1)
animeUser1

# index = []
# for i in similar_user_1[:4]:
#     index.append(i[0])
# animeUser = anime.iloc[index]
# animeUser

anime_id                          name  \
47      22135       Ping Pong The Animation   
149      5040                      One Outs   
101     18115    Magi: The Kingdom of Magic   
268     14513  Magi: The Labyrinth of Magic   

                                      genre type episodes  rating  members  
47              Psychological Seinen Sports   TV       11    8.67    97187  
149             Psychological Seinen Sports   TV       25    8.41    83056  
101  Action Adventure Fantasy Magic Shounen   TV       25    8.50   245026  
268  Action Adventure Fantasy Magic Shounen   TV       25    8.24   317513