# __RECOMMENDATION SYSTEM__

<hr>
<hr>

- Top / Popular Based Filtering
- Content-Based Filtering
- Collaborative Filtering

<img src="https://www.researchgate.net/profile/Lionel_Ngoupeyou_Tondji/publication/323726564/figure/fig5/AS:631605009846299@1527597777415/Content-based-filtering-vs-Collaborative-filtering-Source.png">

In [1]:
import numpy as np
import pandas as pd

## 1. _Content-Based Filtering_

<hr>

- melihat kesamaan item dari kategori dll

<hr>

__A. Cosinus Similarity__

- menghitung kesamaan data berdasarkan value dan pola value

#### ```from sklearn.metrics.pairwise import cosine_similarity```

In [14]:
from sklearn.metrics.pairwise import cosine_similarity 

In [23]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

In [24]:
similarityScore = cosine_similarity([x, y])
similarityScore

array([[1., 1.],
       [1., 1.]])

In [25]:
simDf = pd.DataFrame(
    similarityScore,
    columns=['x', 'y'],
    index= ['x', 'y'])

In [26]:
simDf

x    y
x  1.0  1.0
y  1.0  1.0

In [5]:
x = np.array([1, 1, 1])
y = np.array([1, 2, 1])
similarityScore = cosine_similarity([x, y])
similarityScore

array([[1.        , 0.94280904],
       [0.94280904, 1.        ]])

In [6]:
# data beda elemen namun tiap data elemen sama
x = np.array([1, 1, 1])
y = np.array([2, 2, 2])
similarityScore = cosine_similarity([x, y])
similarityScore

array([[1., 1.],
       [1., 1.]])

In [21]:
x = np.array([1, 2, 3])
y = np.array([5, 5, 5])
similarityScore = cosine_similarity([x, y])
similarityScore

array([[1.       , 0.9258201],
       [0.9258201, 1.       ]])

<hr>

__B. Count Vectorizer__

- bagaimana menghitung cos similarity untuk categorical data (value berupa string)
- Data di-extract untuk menentukan jumlah tiap kata. Jumlah tiap kata dalam data itulah yang dicari cosine similarity-nya
- di sklearn, gunakan ```CountVectorizer```

#### ```from sklearn.feature_extraction.text import CountVectorizer```

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
x = 'Andi Budi Caca'
y = 'Andi Budi Caca'

In [30]:
countvec = CountVectorizer()

In [32]:
c = countvec.fit_transform([x, y])
c

<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [34]:
#kata yg terkandung
countvec.get_feature_names()

['andi', 'budi', 'caca']

In [37]:
# matriks frequency : freq tiap kata di setiap data
mf = c.toarray()
mf

#[[1, 1, 1] => data 1 = andi 1x, budi 1x, caca 1x
#[1, 1, 1]] => data 2 = andi 1x, budi 1x, caca 1x

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [38]:
similarityScore = cosine_similarity(mf)
similarityScore

#       X  Y
#  X [[1., 1.]
#  Y  [1., 1.]]

array([[1., 1.],
       [1., 1.]])


|NO.|NAMABARANG|KATEGORI|MERK|GRADE|COMBINE|
|---|---|---|---|---|---|
|1. |Tamiya A| Mainan | Tamniya |   HIGH | Tamiya A Mainan Tamiya HIGH|

In [39]:
x = 'Andi Budi Caca'
y = 'Andi Budi Budi'
countvec = CountVectorizer()
c = countvec.fit_transform([x, y])
print(countvec.get_feature_names())
print(c.toarray())

similarityScore = cosine_similarity(c.toarray())
print(similarityScore)

['andi', 'budi', 'caca']
[[1 1 1]
 [1 2 0]]
[[1.         0.77459667]
 [0.77459667 1.        ]]


<hr>

### _CONTOH_

- Content-Based Filtering by __*Brand*__ and __*Color*__

In [41]:
df = pd.read_csv('USA_cars_datasets.csv')
df.head()

Unnamed: 0  price      brand    model  year   title_status   mileage  \
0           0   6300     toyota  cruiser  2008  clean vehicle  274117.0   
1           1   2899       ford       se  2011  clean vehicle  190552.0   
2           2   5350      dodge      mpv  2018  clean vehicle   39590.0   
3           3  25000       ford     door  2014  clean vehicle   64146.0   
4           4  27700  chevrolet     1500  2018  clean vehicle    6654.0   

    color                  vin        lot       state country      condition  
0   black    jtezu11f88k007763  159348797  new jersey     usa   10 days left  
1  silver    2fmdk3gc4bbb02217  166951262   tennessee     usa    6 days left  
2  silver    3c4pdcgg5jt346413  167655728     georgia     usa    2 days left  
3    blue    1ftfw1et4efc23745  167753855    virginia     usa  22 hours left  
4     red    3gcpcrec2jg473991  167763266     florida     usa  22 hours left

In [80]:
# create column contains value combinations between brand and color

df['BC'] = df.apply(lambda row: str(row['brand']) + ' ' + str(row['color']), axis=1)
df['MC'] = df['model'] + ' ' +  df['color']
df.head(3)

df[df['BC'] == 'toyota black']

Unnamed: 0  price   brand    model  year   title_status   mileage  color  \
0           0   6300  toyota  cruiser  2008  clean vehicle  274117.0  black   

                   vin        lot       state country     condition  \
0    jtezu11f88k007763  159348797  new jersey     usa  10 days left   

             BC             MC  
0  toyota black  cruiser black

In [50]:
# count vectorizer : hitung kata di tiap data di column BC

cv = CountVectorizer()
cm = cv.fit_transform(df['BC'])

# total kata unik di column BC
print(cv.get_feature_names())

# matrix frequency tiap kata 
print(cm.toarray())
print(cm.toarray()[0])

['acura', 'audi', 'beige', 'benz', 'billet', 'black', 'blue', 'bmw', 'bright', 'brown', 'buick', 'burgundy', 'cadillac', 'cayenne', 'charcoal', 'chevrolet', 'chrysler', 'clearcoat', 'coat', 'color', 'competition', 'crimson', 'dark', 'davidson', 'dodge', 'ford', 'glacier', 'gmc', 'gold', 'gray', 'green', 'guard', 'harley', 'heartland', 'honda', 'hyundai', 'infiniti', 'ingot', 'jaguar', 'jazz', 'jeep', 'kia', 'kona', 'land', 'lexus', 'light', 'lightning', 'lincoln', 'magnetic', 'maroon', 'maserati', 'mazda', 'mercedes', 'metallic', 'morningsky', 'nissan', 'no_color', 'off', 'orange', 'oxford', 'pearl', 'pearlcoat', 'peterbilt', 'phantom', 'platinum', 'purple', 'ram', 'red', 'royal', 'ruby', 'shadow', 'silver', 'super', 'tan', 'tinted', 'toreador', 'toyota', 'tri', 'triple', 'turquoise', 'tuxedo', 'white', 'yellow']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [83]:
# hitung cosine similarity dari tiap data di matrix frequency

similarityScore = cosine_similarity(cm.toarray())
similarityScore[0]

array([1. , 0. , 0. , ..., 0. , 0.5, 0. ])

In [89]:
# gunakan similarity score sebagai data rekomendasi
# misal saya suka mobil data pertama (index ke-0)

# daftar seluruh mobil beserta similarity scorenya
similarCars = list(enumerate(similarityScore[0]))
similarCars # (index, nilai kesamaannya)

[(0, 0.9999999999999998),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.4999999999999999),
 (7, 0.0),
 (8, 0.0),
 (9, 0.4999999999999999),
 (10, 0.0),
 (11, 0.0),
 (12, 0.4999999999999999),
 (13, 0.0),
 (14, 0.4999999999999999),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.4999999999999999),
 (22, 0.4999999999999999),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.4999999999999999),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.0),
 (44, 0.4999999999999999),
 (45, 0.4999999999999999),
 (46, 0.0),
 (47, 0.0),
 (48, 0.0),
 (49, 0.4999999999999999),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.4999999999999999),
 (63, 0.4999999999999999),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),

In [ ]:
# sort berdasarkan similarity-nya
similarCars = sorted(similarCars, key=lambda x: x[1], reverse=True)
similarCars

In [99]:
# 5 mobil yang mirip

similarCars[:6]

[(0, 0.9999999999999998),
 (6, 0.4999999999999999),
 (9, 0.4999999999999999),
 (12, 0.4999999999999999),
 (14, 0.4999999999999999),
 (21, 0.4999999999999999)]

In [102]:
#print(df['BC'].iloc[21])
#df.iloc[[similarCars[:6][i][0] for i in range(0,6)]]

Unnamed: 0  price      brand    model  year   title_status   mileage  \
0            0   6300     toyota  cruiser  2008  clean vehicle  274117.0   
6            6   7300  chevrolet       pk  2010  clean vehicle  149050.0   
9            9   5250       ford      mpv  2017  clean vehicle   63418.0   
12          12  31900  chevrolet     1500  2018  clean vehicle   22909.0   
14          14  20700       ford     door  2013  clean vehicle  100757.0   
21          21   7300        kia    forte  2018  clean vehicle   38823.0   

    color                  vin        lot           state country  \
0   black    jtezu11f88k007763  159348797      new jersey     usa   
6   black    1gcsksea1az121133  167753872         georgia     usa   
9   black    2fmpk3j92hbc12542  167656121           texas     usa   
12  black    3gcukrec0jg176059  167763273       tennessee     usa   
14  black    1ftfw1et7dfa47790  167753916        virginia     usa   
21  black    3kpfl4a79je272611  167801773  north carolina     usa   

        condition               BC             MC  
0    10 days left     toyota black  cruiser black  
6   22 hours left  chevrolet black       pk black  
9     2 days left       ford black      mpv black  
12  22 hours left  chevrolet black     1500 black  
14  22 hours left       ford black     door black  
21    2 days left        kia black    forte black

In [94]:

dfRec = []
for i in similarCars[:6]:
    #print(df['BC'].iloc[i[0]])
    dfRec.append(df.iloc[i[0]])
dfRec = pd.DataFrame(dfRec)
dfRec

Unnamed: 0  price      brand    model  year   title_status   mileage  \
0            0   6300     toyota  cruiser  2008  clean vehicle  274117.0   
6            6   7300  chevrolet       pk  2010  clean vehicle  149050.0   
9            9   5250       ford      mpv  2017  clean vehicle   63418.0   
12          12  31900  chevrolet     1500  2018  clean vehicle   22909.0   
14          14  20700       ford     door  2013  clean vehicle  100757.0   
21          21   7300        kia    forte  2018  clean vehicle   38823.0   

    color                  vin        lot           state country  \
0   black    jtezu11f88k007763  159348797      new jersey     usa   
6   black    1gcsksea1az121133  167753872         georgia     usa   
9   black    2fmpk3j92hbc12542  167656121           texas     usa   
12  black    3gcukrec0jg176059  167763273       tennessee     usa   
14  black    1ftfw1et7dfa47790  167753916        virginia     usa   
21  black    3kpfl4a79je272611  167801773  north carolina     usa   

        condition               BC             MC  
0    10 days left     toyota black  cruiser black  
6   22 hours left  chevrolet black       pk black  
9     2 days left       ford black      mpv black  
12  22 hours left  chevrolet black     1500 black  
14  22 hours left       ford black     door black  
21    2 days left        kia black    forte black